### ISSUE TITLE
CSR generation will fail on maas hosts

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/layer-tls#19]
I believe the failure is due to the unit name being assigned as an IP: directive

```
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40 140213137798816:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:93:name=subjectAltName, value=IP:amused-brass.maas,IP:192.168.100.51,DNS:amused-brass
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40 Easy-RSA error:
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40 Failed to generate request
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40 Traceback (most recent call last):
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40   File "/var/lib/juju/agents/unit-znc-0/charm/hooks/install", line 18, in <module>
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40     main()
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/__init__.py", line 67, in main
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40     bus.dispatch()
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 405, in dispatch
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40     _invoke(other_handlers)
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 388, in _invoke
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40     handler.invoke()
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 269, in invoke
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40     self._action(*args)
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40   File "/var/lib/juju/agents/unit-znc-0/charm/reactive/tls.py", line 54, in check_ca_status
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40     create_certificates()
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40   File "/var/lib/juju/agents/unit-znc-0/charm/reactive/tls.py", line 209, in create_certificates
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40     check_call(split(server))
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40     raise CalledProcessError(retcode, cmd)
unit-znc-0[3165]: 2016-01-19 05:02:13 INFO unit.znc/0.install logger.go:40 subprocess.CalledProcessError: Command '['./easyrsa', '--batch', '--req-cn=amused-brass.maas', '--subject-alt-name=IP:amused-brass.maas,IP:192.168.100.51,DNS:amused-brass', 'build-server-full', 'znc_0', 'nopass', '2>&1']' returned non-zero exit status 1

```

**Comment by chuckbutler** [comment]
Confirmed, IP:amused-brass.maas was the culprit. It appears we will need to get some additional heuristics around this when generating SSL CSR's on MAAS, and determine what our exact validation qualifiers should be.

I can see this getting troublesome on other hosts that are returning non IP as `private-address` or `public-address`

**Comment by mbruzek** [comment]
Great find Chuck. We could create a method that determines the SANs string based on what is passed in, with some regex processing we should be able to tell a valid IP address from a DNS name.  The method would return "IP:{0}".format(address) or "DNS:{0}".format(address) based on the determination of valid_ip(address).

**Comment by chuckbutler** [comment]
i like that idea. I'm pretty sure that IP Validation is already provided in the python batteries, I'll take a look at fixing this sometime this week and follow up with a PR

**Comment by chuckbutler** [comment]
This was done a long time ago as well
