### ISSUE TITLE
config.yaml defaults not carried forward correctly

### ISSUE THREAD

**Issue by jamesbeedy** [juju-solutions/layer-tls#52]
leaving the 'root_certificate' config unspecified in my top layer causes breakage....

```bash
2016-09-07 23:18:00 INFO install Generating a 2048 bit RSA private key
2016-09-07 23:18:00 INFO install .......................................................+++
2016-09-07 23:18:00 INFO install .........................+++
2016-09-07 23:18:00 INFO install writing new private key to '/var/lib/juju/agents/unit-view-2/charm/easy-rsa/easyrsa3/pki/private/ca.key.PmurVrQcEX'
2016-09-07 23:18:00 INFO install -----
2016-09-07 23:18:00 INFO worker.uniter.jujuc server.go:174 running hook tool "juju-log" ["-l" "INFO" "Invoking reactive handler: reactive/tls.py:61:check_ca_status"]
2016-09-07 23:18:00 INFO juju-log Invoking reactive handler: reactive/tls.py:61:check_ca_status
2016-09-07 23:18:00 INFO worker.uniter.jujuc server.go:174 running hook tool "is-leader" ["--format=json"]
2016-09-07 23:18:00 INFO worker.uniter.jujuc server.go:174 running hook tool "juju-log" ["Error decoding string None"]
2016-09-07 23:18:00 INFO juju-log Error decoding string None
2016-09-07 23:18:00 INFO install Traceback (most recent call last):
2016-09-07 23:18:00 INFO install   File "/var/lib/juju/agents/unit-view-2/charm/hooks/install", line 19, in <module>
2016-09-07 23:18:00 INFO install     main()
2016-09-07 23:18:00 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2016-09-07 23:18:00 INFO install     bus.dispatch()
2016-09-07 23:18:00 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
2016-09-07 23:18:00 INFO install     _invoke(other_handlers)
2016-09-07 23:18:00 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
2016-09-07 23:18:00 INFO install     handler.invoke()
2016-09-07 23:18:00 INFO install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
2016-09-07 23:18:00 INFO install     self._action(*args)
2016-09-07 23:18:00 INFO install   File "/var/lib/juju/agents/unit-view-2/charm/reactive/tls.py", line 68, in check_ca_status
2016-09-07 23:18:00 INFO install     root_cert = _decode(config.get('root_certificate'))
2016-09-07 23:18:00 INFO install   File "/var/lib/juju/agents/unit-view-2/charm/reactive/tls.py", line 348, in _decode
2016-09-07 23:18:00 INFO install     return base64.b64decode(encoded)
2016-09-07 23:18:00 INFO install   File "/usr/lib/python3.5/base64.py", line 81, in b64decode
2016-09-07 23:18:00 INFO install     s = _bytes_from_decode_data(s)
2016-09-07 23:18:00 INFO install   File "/usr/lib/python3.5/base64.py", line 46, in _bytes_from_decode_data
2016-09-07 23:18:00 INFO install     "string, not %r" % s.__class__.__name__) from None
2016-09-07 23:18:00 INFO install TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
2016-09-07 23:18:00 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1
```

**Comment by jamesbeedy** [comment]
the following is what ends up in my built charm's config.yaml

```yaml
  "root_certificate":
    "type": "string"
    "default": !!null ""
    "description": |
      The root certificate to use for this grouping of charms.
      If empty (default) the leader will generate a self signed Certificate
      Authority (CA). All certificates will be based on the root certificate.
```
